[C++] Switch to std::any and deprecate antlrcpp::Any
antlr/antlr4 pull request #3395
Opened 2021-12-06 21:31 UTC by jcking

Remove `antlrcpp::Any` in favor of `std::any`. Unfortunately there is no good story for backwards compatibility as `std::any` is a smaller feature set and only supports `static_cast`.

2021-12-06 21:31 UTC, jcking commented
@mike-lischke I kept `antlrcpp::Any` as a type alias to `std::any` to at least make the error people will get more clear and require less changes overall. We can remove `antlrcpp::Any` at some point in the future.

2021-12-07 07:45 UTC, mike-lischke requested changes
The patch looks good, however in the build output I see 3 warnings, that should be fixed. No idea when this creeped in, but I see now:

> /tmp/BaseCppTest-main-1638301471082/TParser.cpp:79:29: warning: explicit capture of 'this' with a capture default of '=' is a C++20 extension [-Wc++20-extensions]
  auto onExit = finally([=, this] {

Then we get  a number of warnings because of the recently deprecated `EMPTY_VOCABULARY`. 

And finally a (probably old) problem with an implicit switch fall through. See the C++ build output in CircleCI.

Can you fix those too?

2021-12-07 14:01 UTC, KvanTTT commented
> /tmp/BaseCppTest-main-1638301471082/TParser.cpp:79:29: warning: explicit capture of 'this' with a capture default of '=' is a C++20 extension [-Wc++20-extensions]

It looks like fixed recently: https://github.com/antlr/antlr4/pull/3393

2021-12-07 14:19 UTC, jcking commented
Fixed everything except EMPTY_VOCABULARY. I'll fix that in a standalone CL. The C++20 warning was fixed in a separate CL after I noticed it. I had misread a preprocessor condition as checking for C++ 17 when it was checking for C++ 20.

2021-12-07 14:50 UTC, mike-lischke approved these changes

2021-12-07 16:49 UTC, parrt commented
Ok, yeah, I think I broke everything yesterday outside of Circleci

2021-12-07 16:50 UTC, merged