fix: #4128 - Prevent generating escape sequences when Windows directories start with  a
antlr/antlr4 pull request #4279
Opened 2023-05-23 05:04 UTC by jimidle

When code generating for Java on Windows, a grammar file may be contained in a subdirectory that starts with a 'u'. Because the generated file is comment with the source file that generated it, and windows path escaping is not used,
then the comment  looks like this in Java:

```java
// Generated from .\users\jim.g by ANTLR 4.13.0
```
 The \u is seen by the Java lexer as an invalid escape sequence because Java processes the whole translation unit through pre-processing and lexing.
 
So, here, just for the template generating the comment, we use Unix style delimiters instead of the backslashes.

NB: I have no Windows box, so I will have to let the GitHub triggers ensure that Windows builds.

Fixes #4128 
Closes #4128

2023-05-30 14:42 UTC, KvanTTT requested changes
Please also add a unit test that covers suggested changes.

2023-05-30 14:42 UTC, KvanTTT commented on tool/src/org/antlr/v4/codegen/model/OutputFile.java
> +		grammarFileName = g.fileName.replace("\\", "/"); // Prevent a path with windows delim and u breaking Java pre-parser on comments
As I understand, this bug is only relevant to Java target. Is it possible to fix the path only for Java target on Windows platform?

2023-05-30 23:19 UTC, jimidle commented
I don’t see the point of fixing it only for Java. Windows supports the
syntax and it would be a total pain, but…

…it changes a generated comment!

So no test as I would have to embed the test somewhere, somehow anyway and
the test running code is fragile.

So I won’t make these changes for the sake of one generated comment that
affects only a few people using Java.

@parrt - can we merge this?

On Tue, May 30, 2023 at 22:42 Ivan Kochurkin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Please also add a unit test that covers suggested changes.
> ------------------------------
>
> In tool/src/org/antlr/v4/codegen/model/OutputFile.java
> <https://github.com/antlr/antlr4/pull/4279#discussion_r1210390903>:
>
> > @@ -26,7 +26,7 @@ public OutputFile(OutputModelFactory factory, String fileName) {
>          super(factory);
>          this.fileName = fileName;
>          Grammar g = factory.getGrammar();
> -		grammarFileName = g.fileName;
> +		grammarFileName = g.fileName.replace("\\", "/"); // Prevent a path with windows delim and u breaking Java pre-parser on comments
>
> As I understand, this bug is only relevant to Java target. Is it possible
> to fix the path only for Java target on Windows platform?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/antlr/antlr4/pull/4279#pullrequestreview-1451133964>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7TMEDEGMRBKPKAWD4L5DXIYBMJANCNFSM6AAAAAAYLKDZ24>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-30 23:31 UTC, parrt commented
`.\users` is hilarious. I can see how that windows path messes with unicode...  I'm ok with the switch.  I wonder if this will trigger a bunch of rebuilds or cause "incompatibilities".  Any thoughts on weird cases like that?

2023-05-31 09:55 UTC, jimidle commented
I’m always a bit wary about generated comments because of that. But the
comment does not put a time stamp on it.

It will show a diff because of the comment, but if you don’t regenerate,
then the generated code won’t change. I thought about having a poll to see
if we should just take the comment out, but I can see that it might be
useful, and I don’t have time to get involved with the ensuing 8 days of
bike shedding !

Java users will be using Maven usually, which tends to rebuild the world
anyway.

It’s six of one and a half dozen of the other I think.

On Wed, May 31, 2023 at 07:31 Terence Parr ***@***.***> wrote:

> .\users is hilarious. I can see how that windows path messes with
> unicode... I'm ok with the switch. I wonder if this will trigger a bunch of
> rebuilds or cause "incompatibilities". Any thoughts on weird cases like
> that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/antlr/antlr4/pull/4279#issuecomment-1569272814>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJ7TMH2JF4FMG754PMXO6TXIZ7M3ANCNFSM6AAAAAAYLKDZ24>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-31 10:55 UTC, KvanTTT commented
> …it changes a generated comment!

Yes, but it still breaks compilation, and some users have encoutered this bug.

> So no test as I would have to embed the test somewhere, somehow anyway and
the test running code is fragile.

The more tests we have the less bugs we'll encounter in the future. Also, current ANTLR test coverege is quite poor.

Please just add the file `uStartingCharInGrammarDoesntBreakCompilation.txt` to [ParserExec](https://github.com/antlr/antlr4/tree/master/runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/ParserExec) with the following content:

```
[type]
Parser

[grammar]
grammar u;
u : 'u' { <writeln("$text")> };

[start]
u

[input]
u

[output]
"""u
"""
```

This test covers all platforms and targets and currently it's failing.

2023-05-31 17:03 UTC, merged

2023-05-31 18:53 UTC, KvanTTT commented
Done: https://github.com/antlr/antlr4/pull/4295